package sudoku;

import java.util.ArrayList;

/**
 * 
 * @author Administrator
 */
public class SudokuFrame extends javax.swing.JFrame {
	private SudokuSolver sudoku;
	private ArrayList<Integer>[][] grid;

	/** Creates new form SudokuFrame */
	public SudokuFrame() {
		initComponents();
		sudoku = new SudokuSolver();
		jTextArea1.requestFocus();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jButton13 = new javax.swing.JButton();
		jButton14 = new javax.swing.JButton();
		jButton15 = new javax.swing.JButton();
		jButton16 = new javax.swing.JButton();
		jButton17 = new javax.swing.JButton();
		jButton18 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jButton19 = new javax.swing.JButton();
		jButton20 = new javax.swing.JButton();
		jButton21 = new javax.swing.JButton();
		jButton22 = new javax.swing.JButton();
		jButton23 = new javax.swing.JButton();
		jButton24 = new javax.swing.JButton();
		jButton25 = new javax.swing.JButton();
		jButton26 = new javax.swing.JButton();
		jButton27 = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jButton28 = new javax.swing.JButton();
		jButton29 = new javax.swing.JButton();
		jButton30 = new javax.swing.JButton();
		jButton31 = new javax.swing.JButton();
		jButton32 = new javax.swing.JButton();
		jButton33 = new javax.swing.JButton();
		jButton34 = new javax.swing.JButton();
		jButton35 = new javax.swing.JButton();
		jButton36 = new javax.swing.JButton();
		jPanel5 = new javax.swing.JPanel();
		jButton37 = new javax.swing.JButton();
		jButton38 = new javax.swing.JButton();
		jButton39 = new javax.swing.JButton();
		jButton40 = new javax.swing.JButton();
		jButton41 = new javax.swing.JButton();
		jButton42 = new javax.swing.JButton();
		jButton43 = new javax.swing.JButton();
		jButton44 = new javax.swing.JButton();
		jButton45 = new javax.swing.JButton();
		jPanel6 = new javax.swing.JPanel();
		jButton46 = new javax.swing.JButton();
		jButton47 = new javax.swing.JButton();
		jButton48 = new javax.swing.JButton();
		jButton49 = new javax.swing.JButton();
		jButton50 = new javax.swing.JButton();
		jButton51 = new javax.swing.JButton();
		jButton52 = new javax.swing.JButton();
		jButton53 = new javax.swing.JButton();
		jButton54 = new javax.swing.JButton();
		jPanel7 = new javax.swing.JPanel();
		jButton55 = new javax.swing.JButton();
		jButton56 = new javax.swing.JButton();
		jButton57 = new javax.swing.JButton();
		jButton58 = new javax.swing.JButton();
		jButton59 = new javax.swing.JButton();
		jButton60 = new javax.swing.JButton();
		jButton61 = new javax.swing.JButton();
		jButton62 = new javax.swing.JButton();
		jButton63 = new javax.swing.JButton();
		jPanel8 = new javax.swing.JPanel();
		jButton64 = new javax.swing.JButton();
		jButton65 = new javax.swing.JButton();
		jButton66 = new javax.swing.JButton();
		jButton67 = new javax.swing.JButton();
		jButton68 = new javax.swing.JButton();
		jButton69 = new javax.swing.JButton();
		jButton70 = new javax.swing.JButton();
		jButton71 = new javax.swing.JButton();
		jButton72 = new javax.swing.JButton();
		jPanel9 = new javax.swing.JPanel();
		jButton73 = new javax.swing.JButton();
		jButton74 = new javax.swing.JButton();
		jButton75 = new javax.swing.JButton();
		jButton76 = new javax.swing.JButton();
		jButton77 = new javax.swing.JButton();
		jButton78 = new javax.swing.JButton();
		jButton79 = new javax.swing.JButton();
		jButton80 = new javax.swing.JButton();
		jButton81 = new javax.swing.JButton();
		jPanel10 = new javax.swing.JPanel();
		jTextArea1 = new javax.swing.JTextArea();
		jPanel11 = new javax.swing.JPanel();
		jPanel12 = new javax.swing.JPanel();
		jButton82 = new javax.swing.JButton();

		getContentPane().setLayout(new java.awt.GridLayout(4, 3));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Sudoku Solver");
		setBackground(new java.awt.Color(51, 51, 255));
		jPanel1.setLayout(new java.awt.GridLayout(3, 3));

		jPanel1.setBackground(new java.awt.Color(0, 102, 255));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel1.add(jButton1);

		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel1.add(jButton2);

		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel1.add(jButton3);

		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel1.add(jButton4);

		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel1.add(jButton5);

		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel1.add(jButton6);

		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});
		jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel1.add(jButton7);

		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});
		jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel1.add(jButton8);

		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});
		jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel1.add(jButton9);

		getContentPane().add(jPanel1);

		jPanel2.setLayout(new java.awt.GridLayout(3, 3));

		jPanel2.setBackground(new java.awt.Color(0, 102, 255));
		jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton10ActionPerformed(evt);
			}
		});
		jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel2.add(jButton10);

		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});
		jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel2.add(jButton11);

		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton12ActionPerformed(evt);
			}
		});
		jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel2.add(jButton12);

		jButton13.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton13ActionPerformed(evt);
			}
		});
		jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel2.add(jButton13);

		jButton14.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton14ActionPerformed(evt);
			}
		});
		jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel2.add(jButton14);

		jButton15.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton15ActionPerformed(evt);
			}
		});
		jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel2.add(jButton15);

		jButton16.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton16ActionPerformed(evt);
			}
		});
		jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel2.add(jButton16);

		jButton17.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton17ActionPerformed(evt);
			}
		});
		jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel2.add(jButton17);

		jButton18.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton18ActionPerformed(evt);
			}
		});
		jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel2.add(jButton18);

		getContentPane().add(jPanel2);

		jPanel3.setLayout(new java.awt.GridLayout(3, 3));

		jPanel3.setBackground(new java.awt.Color(0, 102, 255));
		jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jButton19.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton19ActionPerformed(evt);
			}
		});
		jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel3.add(jButton19);

		jButton20.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton20ActionPerformed(evt);
			}
		});
		jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel3.add(jButton20);

		jButton21.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton21ActionPerformed(evt);
			}
		});
		jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel3.add(jButton21);

		jButton22.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton22ActionPerformed(evt);
			}
		});
		jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel3.add(jButton22);

		jButton23.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton23ActionPerformed(evt);
			}
		});
		jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel3.add(jButton23);

		jButton24.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton24ActionPerformed(evt);
			}
		});
		jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel3.add(jButton24);

		jButton25.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton25ActionPerformed(evt);
			}
		});
		jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel3.add(jButton25);

		jButton26.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton26ActionPerformed(evt);
			}
		});
		jButton26.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel3.add(jButton26);

		jButton27.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton27ActionPerformed(evt);
			}
		});
		jButton27.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel3.add(jButton27);

		getContentPane().add(jPanel3);

		jPanel4.setLayout(new java.awt.GridLayout(3, 3));

		jPanel4.setBackground(new java.awt.Color(0, 102, 255));
		jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jButton28.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton28ActionPerformed(evt);
			}
		});
		jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel4.add(jButton28);

		jButton29.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton29ActionPerformed(evt);
			}
		});
		jButton29.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel4.add(jButton29);

		jButton30.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton30ActionPerformed(evt);
			}
		});
		jButton30.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel4.add(jButton30);

		jButton31.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton31ActionPerformed(evt);
			}
		});
		jButton31.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel4.add(jButton31);

		jButton32.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton32ActionPerformed(evt);
			}
		});
		jButton32.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel4.add(jButton32);

		jButton33.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton33ActionPerformed(evt);
			}
		});
		jButton33.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel4.add(jButton33);

		jButton34.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton34ActionPerformed(evt);
			}
		});
		jButton34.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel4.add(jButton34);

		jButton35.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton35ActionPerformed(evt);
			}
		});
		jButton35.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel4.add(jButton35);

		jButton36.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton36ActionPerformed(evt);
			}
		});
		jButton36.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel4.add(jButton36);

		getContentPane().add(jPanel4);

		jPanel5.setLayout(new java.awt.GridLayout(3, 3));

		jPanel5.setBackground(new java.awt.Color(0, 102, 255));
		jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jButton37.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton37ActionPerformed(evt);
			}
		});
		jButton37.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel5.add(jButton37);

		jButton38.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton38ActionPerformed(evt);
			}
		});
		jButton38.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel5.add(jButton38);

		jButton39.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton39ActionPerformed(evt);
			}
		});
		jButton39.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel5.add(jButton39);

		jButton40.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton40ActionPerformed(evt);
			}
		});
		jButton40.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel5.add(jButton40);

		jButton41.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton41ActionPerformed(evt);
			}
		});
		jButton41.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel5.add(jButton41);

		jButton42.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton42ActionPerformed(evt);
			}
		});
		jButton42.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel5.add(jButton42);

		jButton43.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton43ActionPerformed(evt);
			}
		});

		jPanel5.add(jButton43);

		jButton44.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton44ActionPerformed(evt);
			}
		});
		jButton44.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel5.add(jButton44);

		jButton45.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton45ActionPerformed(evt);
			}
		});
		jButton45.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel5.add(jButton45);

		getContentPane().add(jPanel5);

		jPanel6.setLayout(new java.awt.GridLayout(3, 3));

		jPanel6.setBackground(new java.awt.Color(0, 102, 255));
		jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jButton46.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton46ActionPerformed(evt);
			}
		});
		jButton46.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel6.add(jButton46);

		jButton47.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton47ActionPerformed(evt);
			}
		});
		jButton47.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel6.add(jButton47);

		jButton48.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton48ActionPerformed(evt);
			}
		});
		jButton48.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel6.add(jButton48);

		jButton49.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton49ActionPerformed(evt);
			}
		});
		jButton49.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel6.add(jButton49);

		jButton50.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton50ActionPerformed(evt);
			}
		});
		jButton50.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel6.add(jButton50);

		jButton51.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton51ActionPerformed(evt);
			}
		});
		jButton51.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel6.add(jButton51);

		jButton52.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton52ActionPerformed(evt);
			}
		});
		jButton52.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel6.add(jButton52);

		jButton53.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton53ActionPerformed(evt);
			}
		});
		jButton53.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel6.add(jButton53);

		jButton54.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton54ActionPerformed(evt);
			}
		});
		jButton54.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel6.add(jButton54);

		getContentPane().add(jPanel6);

		jPanel7.setLayout(new java.awt.GridLayout(3, 3));

		jPanel7.setBackground(new java.awt.Color(0, 102, 255));
		jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jButton55.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton55ActionPerformed(evt);
			}
		});
		jButton55.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel7.add(jButton55);

		jButton56.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton56ActionPerformed(evt);
			}
		});
		jButton56.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel7.add(jButton56);

		jButton57.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton57ActionPerformed(evt);
			}
		});
		jButton57.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel7.add(jButton57);

		jButton58.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton58ActionPerformed(evt);
			}
		});
		jButton58.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel7.add(jButton58);

		jButton59.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton59ActionPerformed(evt);
			}
		});
		jButton59.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel7.add(jButton59);

		jButton60.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton60ActionPerformed(evt);
			}
		});
		jButton60.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel7.add(jButton60);

		jButton61.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton61ActionPerformed(evt);
			}
		});
		jButton61.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel7.add(jButton61);

		jButton62.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton62ActionPerformed(evt);
			}
		});
		jButton62.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel7.add(jButton62);

		jButton63.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton63ActionPerformed(evt);
			}
		});
		jButton63.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel7.add(jButton63);

		getContentPane().add(jPanel7);

		jPanel8.setLayout(new java.awt.GridLayout(3, 3));

		jPanel8.setBackground(new java.awt.Color(0, 102, 255));
		jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jButton64.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton64ActionPerformed(evt);
			}
		});
		jButton64.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel8.add(jButton64);

		jButton65.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton65ActionPerformed(evt);
			}
		});
		jButton65.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel8.add(jButton65);

		jButton66.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton66ActionPerformed(evt);
			}
		});
		jButton66.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel8.add(jButton66);

		jButton67.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton67ActionPerformed(evt);
			}
		});
		jButton67.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel8.add(jButton67);

		jButton68.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton68ActionPerformed(evt);
			}
		});
		jButton68.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel8.add(jButton68);

		jButton69.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton69ActionPerformed(evt);
			}
		});
		jButton69.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel8.add(jButton69);

		jButton70.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton70ActionPerformed(evt);
			}
		});
		jButton70.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel8.add(jButton70);

		jButton71.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton71ActionPerformed(evt);
			}
		});
		jButton71.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel8.add(jButton71);

		jButton72.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton72ActionPerformed(evt);
			}
		});
		jButton72.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel8.add(jButton72);

		getContentPane().add(jPanel8);

		jPanel9.setLayout(new java.awt.GridLayout(3, 3));

		jPanel9.setBackground(new java.awt.Color(0, 102, 255));
		jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jButton73.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton73ActionPerformed(evt);
			}
		});
		jButton73.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel9.add(jButton73);

		jButton74.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton74ActionPerformed(evt);
			}
		});
		jButton74.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel9.add(jButton74);

		jButton75.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton75ActionPerformed(evt);
			}
		});
		jButton75.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel9.add(jButton75);

		jButton76.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton76ActionPerformed(evt);
			}
		});
		jButton76.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel9.add(jButton76);

		jButton77.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton77ActionPerformed(evt);
			}
		});
		jButton77.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel9.add(jButton77);

		jButton78.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton78ActionPerformed(evt);
			}
		});
		jButton78.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel9.add(jButton78);

		jButton79.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton79ActionPerformed(evt);
			}
		});
		jButton79.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel9.add(jButton79);

		jButton80.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton80ActionPerformed(evt);
			}
		});
		jButton80.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel9.add(jButton80);

		jButton81.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton81ActionPerformed(evt);
			}
		});
		jButton81.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel9.add(jButton81);

		getContentPane().add(jPanel9);

		jPanel10.setBackground(new java.awt.Color(51, 51, 255));
		jTextArea1.setMinimumSize(new java.awt.Dimension(10, 30));
		jTextArea1.setPreferredSize(new java.awt.Dimension(79, 23));
		jPanel10.add(jTextArea1);

		getContentPane().add(jPanel10);

		jPanel11.setBackground(new java.awt.Color(51, 51, 255));
		getContentPane().add(jPanel11);

		jPanel12.setBackground(new java.awt.Color(51, 51, 255));
		jButton82.setText("Solve");
		jButton82.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton82ActionPerformed(evt);
			}
		});

		jPanel12.add(jButton82);

		getContentPane().add(jPanel12);

		pack();
	}

	private void jButton81ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 8;
		int column = 8;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton80ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 8;
		int column = 7;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton79ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 8;
		int column = 6;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton72ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 8;
		int column = 5;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 8;
		int column = 4;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 8;
		int column = 3;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 8;
		int column = 2;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 8;
		int column = 1;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 8;
		int column = 0;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton78ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 7;
		int column = 8;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton77ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 7;
		int column = 7;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton76ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 7;
		int column = 6;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 7;
		int column = 5;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton68ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 7;
		int column = 4;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 7;
		int column = 3;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 7;
		int column = 2;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 7;
		int column = 1;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 7;
		int column = 0;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton75ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 6;
		int column = 8;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton74ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 6;
		int column = 7;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton73ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 6;
		int column = 6;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 6;
		int column = 5;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 6;
		int column = 4;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 6;
		int column = 3;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 6;
		int column = 2;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 6;
		int column = 1;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 6;
		int column = 0;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 5;
		int column = 8;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 5;
		int column = 7;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 5;
		int column = 6;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 5;
		int column = 5;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 5;
		int column = 4;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 5;
		int column = 3;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 5;
		int column = 2;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 5;
		int column = 1;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 5;
		int column = 0;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 4;
		int column = 8;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 4;
		int column = 7;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 4;
		int column = 6;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 4;
		int column = 5;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 4;
		int column = 4;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 4;
		int column = 3;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 4;
		int column = 2;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 4;
		int column = 1;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 4;
		int column = 0;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 3;
		int column = 8;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 3;
		int column = 7;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 3;
		int column = 6;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 3;
		int column = 5;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 3;
		int column = 4;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 3;
		int column = 3;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 3;
		int column = 2;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 3;
		int column = 1;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 3;
		int column = 0;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 2;
		int column = 8;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 2;
		int column = 7;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 2;
		int column = 6;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 2;
		int column = 5;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 2;
		int column = 4;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 2;
		int column = 3;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 2;
		int column = 2;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 2;
		int column = 1;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 2;
		int column = 0;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 1;
		int column = 8;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 1;
		int column = 7;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 1;
		int column = 6;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 1;
		int column = 5;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 1;
		int column = 4;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 1;
		int column = 3;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 1;
		int column = 2;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 1;
		int column = 1;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 1;
		int column = 0;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 0;
		int column = 8;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 0;
		int column = 7;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 0;
		int column = 6;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 0;
		int column = 5;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 0;
		int column = 4;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 0;
		int column = 3;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 0;
		int column = 2;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextArea1.getText().equals(""))
			return;

		int row = 0;
		int column = 1;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void jButton82ActionPerformed(java.awt.event.ActionEvent evt) {
		jTextArea1.setEnabled(false);
		sudoku.start();
		try {
			Thread.sleep(100);
		} catch (InterruptedException e) {
		}
		;

		if (sudoku.isSolved()) {
			int row = 0;
			int column = 0;
			grid = sudoku.getGrid();
			Integer integer = new Integer(0);

			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton1.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton2.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton3.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton10.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton11.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton12.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton19.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton20.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton21.setText(integer.intValue() + "");

			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton4.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton5.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton6.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton13.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton14.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton15.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton22.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton23.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton24.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);

			jButton7.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton8.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton9.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton16.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton17.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton18.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton25.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton26.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton27.setText(integer.intValue() + "");

			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton28.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton29.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton30.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton37.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton38.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton39.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton46.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton47.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton48.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);

			jButton31.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton32.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton33.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton40.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton41.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton42.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton49.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton50.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton51.setText(integer.intValue() + "");

			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton34.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton35.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton36.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton43.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton44.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton45.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton52.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton53.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton54.setText(integer.intValue() + "");

			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton55.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton56.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton57.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton64.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton65.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton66.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton73.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton74.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton75.setText(integer.intValue() + "");

			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton58.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton59.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton60.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton67.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton68.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton69.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton76.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton77.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton78.setText(integer.intValue() + "");

			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton61.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton62.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton63.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton70.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton71.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton72.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton79.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton80.setText(integer.intValue() + "");
			integer = grid[(int) (row++ / grid.length)][column++
					% grid.length].get(0);
			jButton81.setText(integer.intValue() + "");
		}

	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jTextArea1.getText().equals(""))
			return;

		int row = 0;
		int column = 0;
		sudoku.setVal(row, column, Integer.parseInt(jTextArea1.getText()));

		javax.swing.JButton jbutton = (javax.swing.JButton) evt.getSource();
		jbutton.setText(jTextArea1.getText());
		jbutton.setEnabled(false);

		jTextArea1.setText("");
		jTextArea1.requestFocus();
	}

	private void click(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SudokuFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton17;
	private javax.swing.JButton jButton18;
	private javax.swing.JButton jButton19;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton20;
	private javax.swing.JButton jButton21;
	private javax.swing.JButton jButton22;
	private javax.swing.JButton jButton23;
	private javax.swing.JButton jButton24;
	private javax.swing.JButton jButton25;
	private javax.swing.JButton jButton26;
	private javax.swing.JButton jButton27;
	private javax.swing.JButton jButton28;
	private javax.swing.JButton jButton29;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton30;
	private javax.swing.JButton jButton31;
	private javax.swing.JButton jButton32;
	private javax.swing.JButton jButton33;
	private javax.swing.JButton jButton34;
	private javax.swing.JButton jButton35;
	private javax.swing.JButton jButton36;
	private javax.swing.JButton jButton37;
	private javax.swing.JButton jButton38;
	private javax.swing.JButton jButton39;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton40;
	private javax.swing.JButton jButton41;
	private javax.swing.JButton jButton42;
	private javax.swing.JButton jButton43;
	private javax.swing.JButton jButton44;
	private javax.swing.JButton jButton45;
	private javax.swing.JButton jButton46;
	private javax.swing.JButton jButton47;
	private javax.swing.JButton jButton48;
	private javax.swing.JButton jButton49;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton50;
	private javax.swing.JButton jButton51;
	private javax.swing.JButton jButton52;
	private javax.swing.JButton jButton53;
	private javax.swing.JButton jButton54;
	private javax.swing.JButton jButton55;
	private javax.swing.JButton jButton56;
	private javax.swing.JButton jButton57;
	private javax.swing.JButton jButton58;
	private javax.swing.JButton jButton59;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton60;
	private javax.swing.JButton jButton61;
	private javax.swing.JButton jButton62;
	private javax.swing.JButton jButton63;
	private javax.swing.JButton jButton64;
	private javax.swing.JButton jButton65;
	private javax.swing.JButton jButton66;
	private javax.swing.JButton jButton67;
	private javax.swing.JButton jButton68;
	private javax.swing.JButton jButton69;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton70;
	private javax.swing.JButton jButton71;
	private javax.swing.JButton jButton72;
	private javax.swing.JButton jButton73;
	private javax.swing.JButton jButton74;
	private javax.swing.JButton jButton75;
	private javax.swing.JButton jButton76;
	private javax.swing.JButton jButton77;
	private javax.swing.JButton jButton78;
	private javax.swing.JButton jButton79;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton80;
	private javax.swing.JButton jButton81;
	private javax.swing.JButton jButton82;
	private javax.swing.JButton jButton9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel12;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration
}